In [42]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet, LassoCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler, PolynomialFeatures, OneHotEncoder, LabelEncoder
from sklearn.model_selection import train_test_split, KFold, LeaveOneOut, LeavePOut
from sklearn.compose import ColumnTransformer
import category_encoders as ce

In [3]:
df = pd.read_csv('/Users/fesavaskurt/Python&ML/Kodlarım/Python/datasets/ML Datasets/CarPrice_Assignment.csv')

In [4]:
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [5]:
df.info

<bound method DataFrame.info of      car_ID  symboling                   CarName fueltype aspiration  \
0         1          3        alfa-romero giulia      gas        std
1         2          3       alfa-romero stelvio      gas        std
2         3          1  alfa-romero Quadrifoglio      gas        std
3         4          2               audi 100 ls      gas        std
4         5          2                audi 100ls      gas        std
..      ...        ...                       ...      ...        ...
200     201         -1           volvo 145e (sw)      gas        std
201     202         -1               volvo 144ea      gas      turbo
202     203         -1               volvo 244dl      gas        std
203     204         -1                 volvo 246   diesel      turbo
204     205         -1               volvo 264gl      gas      turbo

    doornumber      carbody drivewheel enginelocation  wheelbase  ...  \
0          two  convertible        rwd          front       88.6  ...
1          two  convertible        rwd          front       88.6  ...
2          two    hatchback        rwd          front       94.5  ...
3         four        sedan        fwd          front       99.8  ...
4         four        sedan        4wd          front       99.4  ...
..         ...          ...        ...            ...        ...  ...
200       four        sedan        rwd          front      109.1  ...
201       four        sedan        rwd          front      109.1  ...
202       four        sedan        rwd          front      109.1  ...
203       four        sedan        rwd          front      109.1  ...
204       four        sedan        rwd          front      109.1  ...

     enginesize  fuelsystem  boreratio  stroke compressionratio horsepower  \
0           130        mpfi       3.47    2.68              9.0        111
1           130        mpfi       3.47    2.68              9.0        111
2           152        mpfi       2.68    3.47              9.0        154
3           109        mpfi       3.19    3.40             10.0        102
4           136        mpfi       3.19    3.40              8.0        115
..          ...         ...        ...     ...              ...        ...
200         141        mpfi       3.78    3.15              9.5        114
201         141        mpfi       3.78    3.15              8.7        160
202         173        mpfi       3.58    2.87              8.8        134
203         145         idi       3.01    3.40             23.0        106
204         141        mpfi       3.78    3.15              9.5        114

     peakrpm citympg  highwaympg    price
0       5000      21          27  13495.0
1       5000      21          27  16500.0
2       5000      19          26  16500.0
3       5500      24          30  13950.0
4       5500      18          22  17450.0
..       ...     ...         ...      ...
200     5400      23          28  16845.0
201     5300      19          25  19045.0
202     5500      18          23  21485.0
203     4800      26          27  22470.0
204     5400      19          25  22625.0

[205 rows x 26 columns]>

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 41.8+ KB

In [7]:
df.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [8]:
df.isnull().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [9]:
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [10]:
df["CarName"].unique()

array(['alfa-romero giulia', 'alfa-romero stelvio',
       'alfa-romero Quadrifoglio', 'audi 100 ls', 'audi 100ls',
       'audi fox', 'audi 5000', 'audi 4000', 'audi 5000s (diesel)',
       'bmw 320i', 'bmw x1', 'bmw x3', 'bmw z4', 'bmw x4', 'bmw x5',
       'chevrolet impala', 'chevrolet monte carlo', 'chevrolet vega 2300',
       'dodge rampage', 'dodge challenger se', 'dodge d200',
       'dodge monaco (sw)', 'dodge colt hardtop', 'dodge colt (sw)',
       'dodge coronet custom', 'dodge dart custom',
       'dodge coronet custom (sw)', 'honda civic', 'honda civic cvcc',
       'honda accord cvcc', 'honda accord lx', 'honda civic 1500 gl',
       'honda accord', 'honda civic 1300', 'honda prelude',
       'honda civic (auto)', 'isuzu MU-X', 'isuzu D-Max ',
       'isuzu D-Max V-Cross', 'jaguar xj', 'jaguar xf', 'jaguar xk',
       'maxda rx3', 'maxda glc deluxe', 'mazda rx2 coupe', 'mazda rx-4',
       'mazda glc deluxe', 'mazda 626', 'mazda glc', 'mazda rx-7 gs',
       'mazda glc 4', 'mazda glc custom l', 'mazda glc custom',
       'buick electra 225 custom', 'buick century luxus (sw)',
       'buick century', 'buick skyhawk', 'buick opel isuzu deluxe',
       'buick skylark', 'buick century special',
       'buick regal sport coupe (turbo)', 'mercury cougar',
       'mitsubishi mirage', 'mitsubishi lancer', 'mitsubishi outlander',
       'mitsubishi g4', 'mitsubishi mirage g4', 'mitsubishi montero',
       'mitsubishi pajero', 'Nissan versa', 'nissan gt-r', 'nissan rogue',
       'nissan latio', 'nissan titan', 'nissan leaf', 'nissan juke',
       'nissan note', 'nissan clipper', 'nissan nv200', 'nissan dayz',
       'nissan fuga', 'nissan otti', 'nissan teana', 'nissan kicks',
       'peugeot 504', 'peugeot 304', 'peugeot 504 (sw)', 'peugeot 604sl',
       'peugeot 505s turbo diesel', 'plymouth fury iii',
       'plymouth cricket', 'plymouth satellite custom (sw)',
       'plymouth fury gran sedan', 'plymouth valiant', 'plymouth duster',
       'porsche macan', 'porcshce panamera', 'porsche cayenne',
       'porsche boxter', 'renault 12tl', 'renault 5 gtl', 'saab 99e',
       'saab 99le', 'saab 99gle', 'subaru', 'subaru dl', 'subaru brz',
       'subaru baja', 'subaru r1', 'subaru r2', 'subaru trezia',
       'subaru tribeca', 'toyota corona mark ii', 'toyota corona',
       'toyota corolla 1200', 'toyota corona hardtop',
       'toyota corolla 1600 (sw)', 'toyota carina', 'toyota mark ii',
       'toyota corolla', 'toyota corolla liftback',
       'toyota celica gt liftback', 'toyota corolla tercel',
       'toyota corona liftback', 'toyota starlet', 'toyota tercel',
       'toyota cressida', 'toyota celica gt', 'toyouta tercel',
       'vokswagen rabbit', 'volkswagen 1131 deluxe sedan',
       'volkswagen model 111', 'volkswagen type 3', 'volkswagen 411 (sw)',
       'volkswagen super beetle', 'volkswagen dasher', 'vw dasher',
       'vw rabbit', 'volkswagen rabbit', 'volkswagen rabbit custom',
       'volvo 145e (sw)', 'volvo 144ea', 'volvo 244dl', 'volvo 245',
       'volvo 264gl', 'volvo diesel', 'volvo 246'], dtype=object)

In [12]:
df = df.drop(columns = ["CarName", "car_ID"])

In [14]:
df[["enginesize", "curbweight", "horsepower", "carwidth", "price"]].describe()

       enginesize   curbweight  horsepower    carwidth         price
count  205.000000   205.000000  205.000000  205.000000    205.000000
mean   126.907317  2555.565854  104.117073   65.907805  13276.710571
std     41.642693   520.680204   39.544167    2.145204   7988.852332
min     61.000000  1488.000000   48.000000   60.300000   5118.000000
25%     97.000000  2145.000000   70.000000   64.100000   7788.000000
50%    120.000000  2414.000000   95.000000   65.500000  10295.000000
75%    141.000000  2935.000000  116.000000   66.900000  16503.000000
max    326.000000  4066.000000  288.000000   72.300000  45400.000000

In [15]:
df.head()

,symboling,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,3,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,2,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   symboling         205 non-null    int64
 1   fueltype          205 non-null    object
 2   aspiration        205 non-null    object
 3   doornumber        205 non-null    object
 4   carbody           205 non-null    object
 5   drivewheel        205 non-null    object
 6   enginelocation    205 non-null    object
 7   wheelbase         205 non-null    float64
 8   carlength         205 non-null    float64
 9   carwidth          205 non-null    float64
 10  carheight         205 non-null    float64
 11  curbweight        205 non-null    int64
 12  enginetype        205 non-null    object
 13  cylindernumber    205 non-null    object
 14  enginesize        205 non-null    int64
 15  fuelsystem        205 non-null    object
 16  boreratio         205 non-null    float64
 17  stroke            205 non-null    float64
 18  compressionratio  205 non-null    float64
 19  horsepower        205 non-null    int64
 20  peakrpm           205 non-null    int64
 21  citympg           205 non-null    int64
 22  highwaympg        205 non-null    int64
 23  price             205 non-null    float64
dtypes: float64(8), int64(7), object(9)
memory usage: 38.6+ KB

In [19]:
numerical_cols = df.select_dtypes(include=["number"]).columns.tolist()
categorical_cols = df.select_dtypes(include=["object", "category", "bool"]).columns.tolist()

In [20]:
df.head(4)

,symboling,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,3,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0

In [21]:
df["fueltype"].unique()

array(['gas', 'diesel'], dtype=object)

In [22]:
df["aspiration"].unique()

array(['std', 'turbo'], dtype=object)

In [32]:
df["fuelsystem"].unique()

array(['mpfi', '2bbl', 'mfi', '1bbl', 'spfi', '4bbl', 'idi', 'spdi'],
      dtype=object)

In [29]:
categorical_cols

['fueltype',
 'aspiration',
 'doornumber',
 'carbody',
 'drivewheel',
 'enginelocation',
 'enginetype',
 'cylindernumber',
 'fuelsystem']

In [33]:
numerical_cols

['symboling',
 'wheelbase',
 'carlength',
 'carwidth',
 'carheight',
 'curbweight',
 'enginesize',
 'boreratio',
 'stroke',
 'compressionratio',
 'horsepower',
 'peakrpm',
 'citympg',
 'highwaympg',
 'price']

In [34]:
X = df[['fueltype',
 'aspiration',
 'doornumber',
 'carbody',
 'drivewheel',
 'enginelocation',
 'enginetype',
 'cylindernumber',
 'fuelsystem','symboling',
 'wheelbase',
 'carlength',
 'carwidth',
 'carheight',
 'curbweight',
 'enginesize',
 'boreratio',
 'stroke',
 'compressionratio',
 'horsepower',
 'peakrpm',
 'citympg',
 'highwaympg',]]
y = df["price"]

In [57]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size= 0.2, random_state= 42
)

In [ ]:
# Encoder tanımla
encoder = ce.BinaryEncoder(cols=['fueltype',
 'aspiration',
 'doornumber',
 'enginelocation'])

# Dönüştür
df_encoded = encoder.fit_transform(df)

In [50]:
df_encoded = pd.get_dummies(df_encoded, columns=['carbody', 'drivewheel', 'enginetype', 'cylindernumber', 'fuelsystem'], drop_first=True)

In [62]:
encoder = ce.BinaryEncoder(cols=['fueltype', 'aspiration', 'doornumber', 'enginelocation'])

X_train = encoder.fit_transform(X_train)
X_test = encoder.transform(X_test)

X_train = pd.get_dummies(
    X_train,
    columns=['carbody', 'drivewheel', 'enginetype', 'cylindernumber', 'fuelsystem'],
    drop_first=True
)

X_test = pd.get_dummies(
    X_test,
    columns=['carbody', 'drivewheel', 'enginetype', 'cylindernumber', 'fuelsystem'],
    drop_first=True
)

X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)

ValueError: X does not contain the columns listed in cols

In [63]:
X_train.select_dtypes(include=['object']).columns

Index([], dtype='object')

In [65]:
regression = LinearRegression()

In [66]:
regression.fit(X_train, y_train)

LinearRegression()

In [67]:
y_pred = regression.predict(X_test)

In [70]:
score = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

In [71]:
print("r2: ", score)
print("mae: ", mae)
print("mse: ", mse)

r2:  0.8906395961699063
mae:  2005.554631321455
mse:  8633350.003370712

In [72]:
train_pred = regression.predict(X_train)

train_r2 = r2_score(y_train, train_pred)
test_r2 = r2_score(y_test, y_pred)

In [73]:
train_r2

0.9476416372236126

In [74]:
test_r2

0.8906395961699063

In [75]:
lasso = Lasso(alpha=0.2)

In [76]:
lasso.fit(X_train, y_train)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.132e+08, tolerance: 9.781e+05
  model = cd_fast.enet_coordinate_descent(

Lasso(alpha=0.2)

In [77]:
y_pred = lasso.predict(X_test)

In [78]:
r2_score(y_test, y_pred)

0.8903204027774234

In [79]:
lasso.coef_

array([-1.54663548e+03,  3.33867341e-11,  1.85878671e+03, -6.92905297e-10,
       -3.04612886e+02,  0.00000000e+00,  1.08404565e+04, -9.43720913e-10,
        9.64640739e+01,  1.08122077e+02, -8.26585032e+01,  5.71714069e+02,
        1.13082178e+02,  3.76503579e+00,  1.24444882e+02, -2.10620978e+03,
       -3.87350928e+03, -2.52150166e+02,  1.24847562e+00,  1.97066801e+00,
       -2.35112688e+02,  1.91848790e+02, -3.76330492e+03, -2.54218358e+03,
       -1.60006167e+03, -3.20961662e+03, -2.33827833e+02,  8.52659521e+02,
       -5.59668769e+03, -2.08708313e+03,  2.18194178e+03,  5.79950229e+02,
       -4.22165861e+03,  1.28245789e+02, -7.37914575e+03, -8.35345641e+03,
       -7.32846382e+03, -1.20557950e+04,  0.00000000e+00,  1.55937909e+02,
       -6.10701269e+02,  3.25065887e+03, -2.63596509e+03,  2.42902046e+02,
       -2.20707914e+03, -4.69644347e+02])

In [84]:
lasso.coef_

array([-1.54663548e+03,  3.33867341e-11,  1.85878671e+03, -6.92905297e-10,
       -3.04612886e+02,  0.00000000e+00,  1.08404565e+04, -9.43720913e-10,
        9.64640739e+01,  1.08122077e+02, -8.26585032e+01,  5.71714069e+02,
        1.13082178e+02,  3.76503579e+00,  1.24444882e+02, -2.10620978e+03,
       -3.87350928e+03, -2.52150166e+02,  1.24847562e+00,  1.97066801e+00,
       -2.35112688e+02,  1.91848790e+02, -3.76330492e+03, -2.54218358e+03,
       -1.60006167e+03, -3.20961662e+03, -2.33827833e+02,  8.52659521e+02,
       -5.59668769e+03, -2.08708313e+03,  2.18194178e+03,  5.79950229e+02,
       -4.22165861e+03,  1.28245789e+02, -7.37914575e+03, -8.35345641e+03,
       -7.32846382e+03, -1.20557950e+04,  0.00000000e+00,  1.55937909e+02,
       -6.10701269e+02,  3.25065887e+03, -2.63596509e+03,  2.42902046e+02,
       -2.20707914e+03, -4.69644347e+02])

In [90]:
feature_names = X_train.columns

for name, coef in zip(feature_names, lasso.coef_):
    feature_zero = print(name, coef)

fueltype_0 -1546.635483618355
fueltype_1 3.3386734093249546e-11
aspiration_0 1858.7867141149545
aspiration_1 -6.92905297322584e-10
doornumber_0 -304.61288585284314
doornumber_1 0.0
enginelocation_0 10840.4565184789
enginelocation_1 -9.43720912780214e-10
symboling 96.464073855878
wheelbase 108.12207718426474
carlength -82.65850318538298
carwidth 571.7140686786825
carheight 113.08217830625571
curbweight 3.7650357881874226
enginesize 124.44488174342219
boreratio -2106.2097824314774
stroke -3873.5092787638923
compressionratio -252.1501658966503
horsepower 1.2484756153950287
peakrpm 1.9706680050052032
citympg -235.1126882150152
highwaympg 191.84878990984487
carbody_hardtop -3763.3049186337926
carbody_hatchback -2542.1835767970997
carbody_sedan -1600.0616659863153
carbody_wagon -3209.6166150629783
drivewheel_fwd -233.82783323926287
drivewheel_rwd 852.6595210819066
enginetype_dohcv -5596.687687001628
enginetype_l -2087.0831317125458
enginetype_ohc 2181.941775461038
enginetype_ohcf 579.9502291687344
enginetype_ohcv -4221.658606470142
enginetype_rotor 128.24578936639205
cylindernumber_five -7379.145745780931
cylindernumber_four -8353.456414978953
cylindernumber_six -7328.463821117199
cylindernumber_twelve -12055.794957118484
cylindernumber_two 0.0
fuelsystem_2bbl 155.93790912942384
fuelsystem_4bbl -610.7012691961862
fuelsystem_idi 3250.6588739333743
fuelsystem_mfi -2635.9650899651074
fuelsystem_mpfi 242.90204630231062
fuelsystem_spdi -2207.079137530898
fuelsystem_spfi -469.64434717624306

In [ ]:
import pandas as pd

coef_df = pd.DataFrame({
    "feature": X_train.columns,
    "coef": lasso.coef_
})

In [94]:
zero_features = coef_df[coef_df["coef"] == 0]

print(zero_features)

               feature  coef
5         doornumber_1   0.0
38  cylindernumber_two   0.0

In [98]:
X_test

,fueltype_0,fueltype_1,aspiration_0,aspiration_1,doornumber_0,doornumber_1,enginelocation_0,enginelocation_1,symboling,wheelbase,...,cylindernumber_six,cylindernumber_twelve,cylindernumber_two,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi
15,1,0,0,1,0,1,0,1,0,103.5,...,True,0,False,False,False,False,0,True,False,0
9,1,0,1,0,1,0,0,1,0,99.5,...,False,0,False,False,False,False,0,True,False,0
100,1,0,0,1,0,1,0,1,0,97.2,...,False,0,False,True,False,False,0,False,False,0
132,1,0,0,1,1,0,0,1,3,99.1,...,False,0,False,False,False,False,0,True,False,0
68,0,1,1,0,0,1,0,1,-1,110.0,...,False,0,False,False,False,True,0,False,False,0
95,1,0,0,1,1,0,0,1,1,94.5,...,False,0,False,True,False,False,0,False,False,0
159,0,1,0,1,0,1,0,1,0,95.7,...,False,0,False,False,False,True,0,False,False,0
162,1,0,0,1,0,1,0,1,0,95.7,...,False,0,False,True,False,False,0,False,False,0
147,1,0,0,1,0,1,0,1,0,97.0,...,False,0,False,False,False,False,0,True,False,0
182,0,1,0,1,1,0,0,1,2,97.3,...,False,0,False,False,False,True,0,False,False,0
191,1,0,0,1,0,1,0,1,0,100.4,...,False,0,False,False,False,False,0,True,False,0
164,1,0,0,1,1,0,0,1,1,94.5,...,False,0,False,True,False,False,0,False,False,0
65,1,0,0,1,0,1,0,1,0,104.9,...,False,0,False,False,False,False,0,True,False,0
175,1,0,0,1,0,1,0,1,-1,102.4,...,False,0,False,False,False,False,0,True,False,0
73,1,0,0,1,0,1,0,1,0,120.9,...,False,0,False,False,False,False,0,True,False,0
152,1,0,0,1,0,1,0,1,1,95.7,...,False,0,False,True,False,False,0,False,False,0
18,1,0,0,1,1,0,0,1,2,88.4,...,False,0,False,True,False,False,0,False,False,0
82,1,0,1,0,1,0,0,1,3,95.9,...,False,0,False,False,False,False,0,False,True,0
86,1,0,0,1,0,1,0,1,1,96.3,...,False,0,False,True,False,False,0,False,False,0
143,1,0,0,1,0,1,0,1,0,97.2,...,False,0,False,False,False,False,0,True,False,0
60,1,0,0,1,0,1,0,1,0,98.8,...,False,0,False,True,False,False,0,False,False,0
101,1,0,0,1,0,1,0,1,0,100.4,...,True,0,False,False,False,False,0,True,False,0
98,1,0,0,1,1,0,0,1,2,95.1,...,False,0,False,True,False,False,0,False,False,0
30,1,0,0,1,1,0,0,1,2,86.6,...,False,0,False,False,False,False,0,False,False,0
25,1,0,0,1,0,1,0,1,1,93.7,...,False,0,False,True,False,False,0,False,False,0
16,1,0,0,1,1,0,0,1,0,103.5,...,True,0,False,False,False,False,0,True,False,0
168,1,0,0,1,1,0,0,1,2,98.4,...,False,0,False,False,False,False,0,True,False,0
195,1,0,0,1,0,1,0,1,-1,104.3,...,False,0,False,False,False,False,0,True,False,0
97,1,0,0,1,0,1,0,1,1,94.5,...,False,0,False,True,False,False,0,False,False,0
194,1,0,0,1,0,1,0,1,-2,104.3,...,False,0,False,False,False,False,0,True,False,0
67,0,1,1,0,0,1,0,1,-1,110.0,...,False,0,False,False,False,True,0,False,False,0
120,1,0,0,1,0,1,0,1,1,93.7,...,False,0,False,True,False,False,0,False,False,0
154,1,0,0,1,0,1,0,1,0,95.7,...,False,0,False,True,False,False,0,False,False,0
202,1,0,0,1,0,1,0,1,-1,109.1,...,True,0,False,False,False,False,0,True,False,0
79,1,0,1,0,1,0,0,1,1,93.0,...,False,0,False,False,False,False,0,False,True,0
69,0,1,1,0,1,0,0,1,0,106.7,...,False,0,False,False,False,True,0,False,False,0
145,1,0,1,0,0,1,0,1,0,97.0,...,False,0,False,False,False,False,0,True,False,0
55,1,0,0,1,1,0,0,1,3,95.3,...,False,0,True,False,True,False,0,False,False,0
45,1,0,0,1,0,1,0,1,0,94.5,...,False,0,False,True,False,False,0,False,False,0
84,1,0,1,0,1,0,0,1,3,95.9,...,False,0,False,False,False,False,0,False,True,0
146,1,0,0,1,0,1,0,1,0,97.0,...,False,0,False,True,False,False,0,False,False,0

In [99]:
X_train = X_train.drop(columns=["doornumber_1"])
X_test = X_test.drop(columns=["doornumber_1"])

In [100]:
regression = LinearRegression()
regression.fit(X_train, y_train)
y_pred = regression.predict(X_test)
score = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

In [101]:
print("r2: ", score)
print("mae: ", mae)
print("mse: ", mse)

r2:  0.8906395961701927
mae:  2005.5546313180873
mse:  8633350.003348095