In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("/Users/fesavaskurt/Python&ML/Kodlarım/Python/datasets/ML Datasets/13-car_evaluation.csv")

In [3]:
df.head()

   vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [4]:
df = df.rename(columns={
    "vhigh": "buying",
    "vhigh.1": "maint",
    "2": "doors",
    "2.1": "persons",
    "small": "lug_boot",
    "low": "safety",
    "unacc": "decision"
                        })

In [5]:
df

     buying  maint  doors persons lug_boot safety decision
0     vhigh  vhigh      2       2    small    med    unacc
1     vhigh  vhigh      2       2    small   high    unacc
2     vhigh  vhigh      2       2      med    low    unacc
3     vhigh  vhigh      2       2      med    med    unacc
4     vhigh  vhigh      2       2      med   high    unacc
...     ...    ...    ...     ...      ...    ...      ...
1722    low    low  5more    more      med    med     good
1723    low    low  5more    more      med   high    vgood
1724    low    low  5more    more      big    low    unacc
1725    low    low  5more    more      big    med     good
1726    low    low  5more    more      big   high    vgood

[1727 rows x 7 columns]

In [6]:
df.shape

(1727, 7)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1727 entries, 0 to 1726
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   buying    1727 non-null   object
 1   maint     1727 non-null   object
 2   doors     1727 non-null   object
 3   persons   1727 non-null   object
 4   lug_boot  1727 non-null   object
 5   safety    1727 non-null   object
 6   decision  1727 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB

In [8]:
df.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
decision    0
dtype: int64

In [9]:
df["decision"].value_counts()

decision
unacc    1209
acc       384
good       69
vgood      65
Name: count, dtype: int64

In [11]:
df["buying"].unique()

array(['vhigh', 'high', 'med', 'low'], dtype=object)

In [12]:
df["maint"].unique()

array(['vhigh', 'high', 'med', 'low'], dtype=object)

In [13]:
df["doors"].unique()

array(['2', '3', '4', '5more'], dtype=object)

In [14]:
df["lug_boot"].unique()

array(['small', 'med', 'big'], dtype=object)

In [15]:
df["safety"].unique()

array(['med', 'high', 'low'], dtype=object)

In [16]:
df["decision"].unique()

array(['unacc', 'acc', 'vgood', 'good'], dtype=object)

In [17]:
from sklearn.preprocessing import OrdinalEncoder